dest = "dist/"
destOfWeb = "dist/web/"
destOfPdf = "dist/pdf/"

srcOfServer = "src/server"
srcOfClient = "src/client/"
srcOfDebug = "src/debug/"
srcOfHtml = "src/client/html/*"

test = "test/"

cli = 'cli/'
